name: EarShot
favicon: null
layout_spectrum: 0.50256
typography_spectrum: 0.12884
title: 'EarShot: Must listen audio from the best storytellers on the internet'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#192f3a'
    - '#b4cc9d'
    - '#b28a9d'
    - '#b15198'
    - '#2f593c'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
