name: EarShot
favicon: null
layout_spectrum: 0.50256
typography_spectrum: 0.12884
title: 'EarShot: Must listen audio from the best storytellers on the internet'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#716765'
    - '#f3ece2'
    - '#a0968d'
    - '#312c28'
    - '#bcb4a7'
  brandStrength: 0.9335565036162734
  lightness: 0.9310129869263619
  saturation: 0.4188316271174699
  rhythmicContrast: 0.4166946515906602
purpose: []
