name: EarShot
favicon: null
layout_spectrum: 0.75876
typography_spectrum: 0.1254
title: 'EarShot: Must listen audio from the best storytellers on the internet'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76794748-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f7fc'
    - '#c0c0c0'
    - '#7a7d84'
    - '#0d0502'
    - '#b5651c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
