name: EarShot
favicon: null
layout_spectrum: 0.75255
typography_spectrum: 0.49575
title: EarShot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9335565036162734
  lightness: 0.9310129869263619
  saturation: 0.4188316271174699
  rhythmicContrast: 0.4166946515906602
purpose: []
